include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - prefer_const_constructors
    - avoid_print
    - prefer_final_fields
    - prefer_const_literals_to_create_immutables
    - avoid_redundant_argument_values
    - avoid_unnecessary_containers
    - avoid_function_literals_in_foreach_calls
    - prefer_final_locals
    - prefer_single_quotes
    - unnecessary_this
    - prefer_const_declarations
    - avoid_multiple_declarations_per_line

analyzer:
  errors:
    prefer_const_constructors: warning